### ISSUE TITLE
Extract svg function as external loader

### ISSUE THREAD

**Issue by eylles** [freevo/kaa-imlib2#1]
I just recently discovered your repo, being part of the board of www.github.com/nsxiv/nsxiv i can't but notice your repo has the ability to load svgs with imlib2, there was a patch for sxiv that could load svg images but only provided partial support (couldn't do it in thumbnail mode), it was discussed and the decision was set that writing an svg loader for imlib2 was the way to go. However to date no one has taken the initiative so it would be really great if you could start a repo to extract the svg module into a "generic" image loader for imlib2, we are willing to provide asistance on the task.

**Comment by Dischi** [comment]
We bypass imlib2 for svg files. The logic is only in Python: load the SVG into a memory buffer and afterwards, create an imlib2 object based on that raw buffer. Our hack does not work for imlib2 because we do not even use the same programing language,
